--!strict
--!optimize 2
--!native

return {
	anatomyInstance = require(script.anatomyInstance),
	anatomyPart = require(script.anatomyPart),
	anatomySocket = require(script.anatomySocket),
	anatomySurface = require(script.anatomySurface),
	anatomyTemplate = require(script.anatomyTemplate),
	socketBinding = require(script.socketBinding),
	socketEndpoint = require(script.socketEndpoint),
	socketMount = require(script.socketMount),
}
